language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
      - freetds-dev
cache:
  - pip: true
  - directories:
      - ./stethoscope/ui/node_modules
install:
  - nvm install 6.9.5
  - nvm use 6.9.5
  - make install-node-requirements
  - make install-python-requirements
script:
  - pytest
  - make test-js
