language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env: TEST_SUITE=py
matrix:
  include:
    env: TEST_SUITE=js
addons:
  apt:
    packages:
      - freetds-dev
cache:
  pip: true
  directories:
    - ./stethoscope/ui/node_modules
before_install:
  - nvm install 6.9.5
install:
  - pip install tox-travis
  - if [[ "$TEST_SUITE" == "js" ]]; then make install-node-requirements; fi
script:
  - if [[ "$TEST_SUITE" == "js" ]]; then make test-js; else tox; fi
